# Generated by Django 5.1.15 on 2026-06-22 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, help_text='Можно указать emoji (например 🏎️) — используется на карточках главной страницы.', max_length=50, verbose_name='Иконка (emoji или css-класс)')),
                ('unit_label', models.CharField(blank=True, help_text='Например: км/ч, $, кг, баллы. Используется в карточках и таблицах.', max_length=50, verbose_name='Подпись единицы измерения рекорда')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория рекорда',
                'verbose_name_plural': 'Категории рекордов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название модели')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Слаг')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('top_speed_kmh', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Макс. скорость (км/ч)')),
                ('power_hp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность (л.с.)')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена ($)')),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Масса (кг)')),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина (мм)')),
                ('acceleration_0_100', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Разгон 0-100 км/ч (сек)')),
                ('reliability_score', models.DecimalField(blank=True, decimal_places=1, help_text='Экспертная или агрегированная оценка надёжности.', max_digits=5, null=True, verbose_name='Индекс надёжности (0-100)')),
                ('eco_score', models.DecimalField(blank=True, decimal_places=1, help_text='Чем выше — тем чище технология/меньше выбросов.', max_digits=5, null=True, verbose_name='Индекс экологичности (0-100)')),
                ('tech_score', models.DecimalField(blank=True, decimal_places=1, help_text='Оценка инновационности: автопилот, материалы, электроника.', max_digits=5, null=True, verbose_name='Индекс технологичности (0-100)')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электричество'), ('hybrid', 'Гибрид'), ('hydrogen', 'Водород'), ('other', 'Другое')], default='petrol', max_length=20, verbose_name='Тип топлива')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('record_category', models.ForeignKey(blank=True, help_text='Категория, в которой эта модель в первую очередь известна.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_cars', to='records.category', verbose_name='Основная рекордная категория')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-year', 'manufacturer'],
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Ключ сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('cars', models.ManyToManyField(related_name='comparisons', to='records.car', verbose_name='Автомобили')),
                ('user', models.ForeignKey(blank=True, help_text='Может быть пустым для анонимных сравнений.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сравнение',
                'verbose_name_plural': 'Сравнения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='records.car', verbose_name='Автомобиль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Значение рекорда')),
                ('unit', models.CharField(help_text='км/ч, $, л.с., кг и т.д.', max_length=30, verbose_name='Единица измерения')),
                ('date_set', models.DateField(verbose_name='Дата установления рекорда')),
                ('source', models.CharField(help_text='Название организации или ссылка, подтверждающая рекорд (например, Guinness World Records).', max_length=300, verbose_name='Источник')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_current', models.BooleanField(default=True, help_text='Снимите галочку, если рекорд побит и больше не актуален.', verbose_name='Действующий рекорд')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='records.car', verbose_name='Автомобиль')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='records.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Рекорд',
                'verbose_name_plural': 'Рекорды',
                'ordering': ['-date_set'],
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['manufacturer'], name='records_car_manufac_efe643_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['year'], name='records_car_year_edade4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'car')},
        ),
    ]
